addons:
  apt:
    packages:
      - cmake-data
      - cmake
      - libfreeimage3
      - libfreeimage-dev 
      - libboost-filesystem1.54
      - libboost-program-options1.54
      - clang
      - python
      - lcov

install:
  - gem install coveralls-lcov

before_script:
  - lcov --directory . --zerocounters

script:
  - cmake .
  - make
  - lcov --initial --no-external --directory . --capture --output-file coverage.base.info
  - ./test/runUnitTests

after_success:
  - lcov --no-external --directory . --capture --output-file coverage.info
  - lcov --add-tracefile coverage.base.info --add-tracefile coverage.info --output-file coverage.merged.info
  - lcov -r coverage.merged.info '/usr/include/*' 'googletest-src/*' 'googletest/*' 'test/*' -o coverage.merged.info
  - lcov --list coverage.merged.info
  - coveralls-lcov coverage.merged.info
  